### PR TITLE
feat: Migrate deprecated guard to sample

### PR DESCRIPTION
**Pull request by SQReder**
Get rid of deprecated `guard` operator

-----
<a href="https://stackblitz.com/~/github/sqreder/effector-forms/tree/master">Review PR in StackBlitz Codeflow</a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/sqreder/effector-forms/tree/master)._

### CODE REVIEW

**Comment by SQReder** [comment]
Should it? I just migrate guard that have been deprecated in v22 already
Minimally useful PR

**Comment by bitkovdev** [comment]
I think it should be, since the package still uses version 22 of effector, and it wouldn’t hurt to update it.

**Comment by bitkovdev** [comment]
Yes, that's what I meant. Well, you will still have to update over time)

**Comment by SQReder** [comment]
Anyway, I don't want to take responsibility for v23 migration, so want changes to be as small as possible. Maybe I'll make another PR with migration done right, maybe not

**Pull request closed without merging**
